while True:
    name = input("Enter the name you wish to use for your character: ")

    print()

    ans = input("Welcome to this new adventure, " + name + ". Are you ready to persevere through the hard times headed your way?  (yes / no): ")

    print()

    if ans == "yes" or ans == "Yes":
        ans1 = input(name + ", you were involved in a shipwreck out in the Indian Ocean and have washed up on what appears to be an unhabited island. Everyone on the ship has died, and you are the lone survivor. You then see a large cave opening about 50 feet away from the shore. Do you wish to enter? (yes / no): ")
        if ans1 == "yes" or ans1 == "Yes":
            print()
            input("You have entered Diddy's lair. You lose. Enter any key to restart & try again.")
            print()
            print()
            print()
            print()
            print()
        elif ans1 == "no" or ans1 == "No":
            print()
            ans2 = input("You now begin to roam around, and start to become hungry & thirsty. Finally, you stumble upon a stream of water to drink from. Do you wish to drink from it? (yes / no): ")
            if ans2 == "yes" or ans2 == "Yes":
                print()
                print("Let's go! Your thirst has been quenched.")
                print()
                ans3 = input("You continue to roam the island, and come to a stopping point. To your left there are berries hanging off of a bush, and to your right, a squirrel you could hunt and cook. Do you wish to go to your left or right first? (left / right): ")
                if ans3 == "left" or ans3 == "Left":
                    print()
                    input("You ate the berries, and have died from poison. You lose. Press any key to restart & try again.")
                    print()
                    print()
                    print()
                    print()
                    print()
                elif ans3 == "right" or ans3 == "Right":
                    print()
                    print("Great! You hunt and kill the squirrel.")
                    print()
                    ans4 = input("Do you wish to find wood and rocks to start a fire to cook the squirrel, or eat it raw? (cook / raw): ")
                    if ans4 == "cook" or ans4 == "Cook":
                        print()
                        ans5 = input("You found wood and rocks to create a fire, and began to eat your meal when a young girl approaches you. She looks like she has lived in the wild her entire life. She points at your food, and asks if she can have some. Do you let her have some and stay with you? (yes / no): ")
                        if ans5 == "yes" or ans5 == "Yes":
                            print()
                            input("You guys had a great meal, and socialized throughout the rest of the day. Then, in your sleep you were killed by the girl who fooled you. Something makes me think you're not supposed to be on this island. You lose. Press any key to restart & try again.")
                            print()
                            print()
                            print()
                            print()
                            print()
                        elif ans5 == "no" or ans5 == "No":
                            print()
                            ans6 = input("You run the girl off, and do not see her again for days. Eventually you begin to roam around the island, and as you're walking along the coast, your foot hits something hard in the sand. You search the sand, and find a gun. Do you pick it up? (yes / no): ")
                            if ans6 == "yes" or ans6 == "Yes":
                                print()
                                print("You picked up the gun, and notice it is fully loaded. You store it in your backpack to be safe.")
                                print()
                                ans7 = input("You begin to roam the island one day when a mysterious man appears at the cave opening. He then fades back into the cave. Do you follow him into the cave? (yes / no)")
                                if ans7 == "yes" or ans7 == "Yes":
                                    print()
                                    ans9 = input("Do you follow the man into the cave with your gun equipped? (yes / no): ")
                                    if ans9 == "yes" or ans9 == "Yes":
                                        print()
                                        ans10 = input("you follow the mysterious man inside and see it is Sean Diddy Combs secret lair! You see all his kidnapped humans. You have a clear shot, do you take it, or just let it slip? (yes / no): ")
                                        if ans10 == "yes" or ans10 == "Yes":
                                            print()
                                            print()
                                            print()
                                            print()
                                            print()
                                            print("You are a hero! You saved countless children, and when you return home you are nominated for the nobel peace price, and become a millionare!")
                                            print()
                                            break
                                        elif ans10 == "no" or ans10 == "No":
                                            print()
                                            print("Before you can catch a peak of the mysterious man, you are shot and killed in cold blood. You lose. Press any key to restart & try again.")
                                            print()
                                            print()
                                            print()
                                            print()
                                            print()
                                        else:
                                            print()
                                            print("invalid text entry. You lose. Press any key to restart and try again.")
                                            print()
                                            print()
                                            print()
                                            print()
                                            print()
                                elif ans7 == "no" or ans7 == "No":
                                    print()
                                    print("You avoid the cave and return to base. In the middle of the night you are kidnapped and killed. You lose. Press any key to restart & try again.")
                                    print()
                                    print()
                                    print()
                                    print()
                                    print()
                                else:
                                    print()
                                    input("Invalid text entry. You lose. Press any key to restart & try again.")
                                    print()
                                    print()
                                    print()
                                    print()
                                    print()
                            elif ans6 == "no" or ans6 == "No":
                                print()
                                print("You choose to leave the gun in the sand, and move on.")
                                print()
                                ans8 = input("You begin to roam the island one day when a mysterious man appears at the cave opening. He then fades back into the cave. Do you follow him into the cave? (yes / no)")
                                if ans8 == "Yes" or ans8 == "yes":
                                    print()
                                    print("Before you can catch a peak of the mysterious man, you are shot and killed in cold blood. you lose. Press any key to restart & try again.")
                                    print()
                                    print()
                                    print()
                                    print()
                                    print()
                                elif ans8 == "no" or ans8 == "No":
                                    print()
                                    print("You avoid the layer and return to base. In your sleep you are kidnapped and killed. You lose. Press any key to restart & try again.")
                                    print()
                                    print()
                                    print()
                                    print()
                                    print()
                                else:
                                    print()
                                    input("Invalid text entry. You lose. Press any key to restart & try again.")
                                    print()
                                    print()
                                    print()
                                    print()
                                    print()
                            else:
                                print()
                                input("Invalid text entry. You lose. Press any key to restart & try again.")
                                print()
                                print()
                                print()
                                print()
                                print()
                        else:
                            print()
                            input("Invalid text entry. You lose. Press any key to restart & try again.")
                            print()
                            print()
                            print()
                            print()
                            print()
                    elif ans4 == "raw" or ans4 == "Raw":
                        print()
                        input("You have died of food poisoning. You lose. Press any key to restart & try again.")
                        print()
                        print()
                        print()
                        print()
                        print() 
                    else:
                        print()
                        input("Invalid text entry. You lose. Press any key to restart & try again.")
                        print()
                        print()
                        print()
                        print()
                        print()
                else:
                    print()
                    input("Invalid text entry. You lose. Press any key to restart & try again.")
                    print()
                    print()
                    print()
                    print()
                    print()
            elif ans2 == "no" or ans2 == "No":
                print()
                input("You have died of dehydration. You lose. Press any key to restart & try again.")
                print()
                print()
                print()
                print()
                print()
            else:
                print()
                input("Invalid text entry. You lose. Press any key to restart & try again.")
                print()
                print()
                print()
                print()
                print()
        else:
            print()
            input("Invalid text entry. You lose. Press any key to restart & try again.")
            print()
            print()
            print()
            print()
            print()
    elif ans == "no" or ans == "No":
        print()
        input("You lose. Press any key to restart & try again.")
        print()
        print()
        print()
        print()
        print()
    else:
        print()
        input("Invalid text entry. You lose. Press any key to restart & try again.")
        print()
        print()
        print()
        print()
        print()
        
input("Congratulations on beating my game. Press any key to exit the program.")
exit

